# Generated by Django 6.0.4 on 2026-04-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commercial_register',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم السجل التجاري'),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='رقم التعريف الوطني'),
        ),
    ]
