# Generated by Django 6.0.4 on 2026-04-19 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_commercial_register_user_national_id'),
        ('transactions', '0002_alter_transaction_buyer_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CREDIT', 'إيداع'), ('DEBIT', 'خصم'), ('FREEZE', 'تجميد'), ('UNFREEZE', 'فك تجميد'), ('RELEASE', 'تحرير')], max_length=10, verbose_name='النوع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الرصيد بعد العملية')),
                ('description', models.CharField(max_length=255, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transaction', verbose_name='الصفقة')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_log', to='accounts.wallet', verbose_name='المحفظة')),
            ],
            options={
                'verbose_name': 'سجل المحفظة',
                'verbose_name_plural': 'سجلات المحفظة',
                'ordering': ['-created_at'],
            },
        ),
    ]
