# Generated by Django 6.0.4 on 2026-04-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='balance_before',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الرصيد قبل العملية'),
        ),
    ]
