# Generated by Django 6.0.4 on 2026-05-02 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_wallettransaction_balance_before'),
        ('transactions', '0002_alter_transaction_buyer_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد')),
                ('total_transactions', models.IntegerField(default=0, verbose_name='إجمالي الصفقات')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'سلة AmanPay',
            },
        ),
        migrations.CreateModel(
            name='CommissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ الأصلي')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نسبة العمولة')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ العمولة')),
                ('seller_received', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المحوّل للبائع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='transactions.transaction', verbose_name='الصفقة')),
            ],
            options={
                'verbose_name': 'سجل العمولة',
                'verbose_name_plural': 'سجلات العمولات',
            },
        ),
    ]
