# Generated by Django 6.0.4 on 2026-04-11 17:11

import django.core.validators
import django.db.models.deletion
import transactions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=transactions.models._generate_transaction_code, editable=False, max_length=6, unique=True, verbose_name='كود المعاملة')),
                ('product_name', models.CharField(max_length=255, verbose_name='اسم المنتج')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('status', models.CharField(choices=[('PENDING', 'في الانتظار'), ('FUNDED', 'ممول'), ('SHIPPED', 'تم الشحن'), ('DELIVERED', 'تم التسليم'), ('COMPLETED', 'مكتمل'), ('DISPUTED', 'متنازع عليه'), ('REFUNDED', 'مسترجع'), ('CANCELLED', 'ملغى')], default='PENDING', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('release_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإفراج عن المبلغ')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='المشتري')),
                ('delivery_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='شركة التوصيل')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='البائع')),
            ],
            options={
                'verbose_name': 'معاملة',
                'verbose_name_plural': 'المعاملات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم')),
                ('comment', models.TextField(blank=True, verbose_name='التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL, verbose_name='المقيِّم')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL, verbose_name='البائع')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='transactions.transaction', verbose_name='المعاملة')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
                'ordering': ['-created_at'],
            },
        ),
    ]
