# Generated by Django 6.0.4 on 2026-05-29 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_buyer_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='dispute_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاطلاع على النزاع'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='dispute_acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_acknowledged', to=settings.AUTH_USER_MODEL, verbose_name='من اطّلع على النزاع'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='dispute_opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ فتح النزاع'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='dispute_opened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_opened', to=settings.AUTH_USER_MODEL, verbose_name='فاتح النزاع'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='dispute_reason',
            field=models.TextField(blank=True, null=True, verbose_name='وصف النزاع'),
        ),
    ]
