# Generated by Django 6.0.4 on 2026-06-24 17:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_dispute_acknowledged_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('10000')), django.core.validators.MaxValueValidator(Decimal('1000000'))], verbose_name='المبلغ'),
        ),
    ]
